import "./globals.css";
import type { Metadata } from "next";
import { Header } from "@/components/header/page";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/provider/AuthProvider";
import { ApolloProviderWrapper } from "../provider/ApolloProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ApolloProviderWrapper>
            <Header />
            {children}
          </ApolloProviderWrapper>
        </NextAuthProvider>
      </body>
    </html>
  );
}
